In [313]:
import pandas as pd
from ipywidgets import interact
import re
from ipywidgets import widgets

In [314]:
!wget "https://raw.githubusercontent.com/faisalanshory/DigiLABS-CodingChallenge/main/Dataset/SocMed_Geographic.xlsx"
!wget "https://raw.githubusercontent.com/faisalanshory/DigiLABS-CodingChallenge/main/Dataset/WorldPopulation2020_Country_WorldBank.xlsx"

--2022-06-11 07:39:31--  https://raw.githubusercontent.com/faisalanshory/DigiLABS-CodingChallenge/main/Dataset/SocMed_Geographic.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19136 (19K) [application/octet-stream]
Saving to: ‘SocMed_Geographic.xlsx’

SocMed_Geographic.x 100%[===================>]  18.69K  --.-KB/s    in 0.001s

2022-06-11 07:39:31 (14.7 MB/s) - ‘SocMed_Geographic.xlsx’ saved [19136/19136]

--2022-06-11 07:39:31--  https://raw.githubusercontent.com/faisalanshory/DigiLABS-CodingChallenge/main/Dataset/WorldPopulation2020_Country_WorldBank.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9855 (9.6K) [application/octet-stream]
Saving to: ‘WorldPopulation2020_Country_WorldBank.xlsx’

WorldPopulation2020 100%[===================>]   9.62K  --.-KB/s    in 0s

2022-06-11 07:39:32 (71.6 MB/s) - ‘WorldPopulation2020_Country_WorldBank.xlsx’ saved [9855/9855]

# **Data Wrangling**

In [315]:
#Read Excel File
df = pd.read_excel("/content/SocMed_Geographic.xlsx", sheet_name="Sheet1")
df.head(10)

,Social Media Platform,Number of users,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,United States,Indonesia,Singapore,China,India,Vietnam,Philippines,Bangladesh
1,Bilibili,NaN,NaN,NaN,"27400000 (2019, 30)",NaN,NaN,NaN,NaN
2,Facebook,"190000000 (2020, 31)","120000000 (2020, 31)","4450000 (2020, 32)","3000000 (2020, 36)","280000000 (2020, 31)","63000000 (2020, 31)","72000000 (2020, 31)","37000000 (2020, 31)"
3,Instagram,"107000000 (2020, 33)","5984000,0 (2020, 34)","2110000 (2020, 35)","3600000 (2020, 37)","88000000 (2020, 38)","8000000 (2019, 39)","11000,00 (2020, 38)","1 676 100 (2019, 40)"
4,Linkedln,"160000000 (2020, 41)","1524000,0 (2020, 42)","2 682 000 (2019, 43)","5397000 (2019, 44)","62000000 (2020, 45)","3 087 500 (2019, 46)","2773485 (2019, 47)","2 990 000 (2019, 48)"
5,Tencent QQ,NaN,NaN,NaN,"659100000 (2020, 49)",NaN,NaN,NaN,NaN
6,Tik Tok,"45400000 (2020, 50)","81000000 (2020, 51)","800,000‬ (2020, 52)","400000000 (2020, 53)","120000,000 (2019, 54)","12000000 (2019, 55)",NaN,NaN
7,Twitter,"55700000 (2019, 56)","11800000 (2020, 57)","1370000 (2020, 58)","3200000 (2020, 59)","1315000,0 (2020, 57)","127000000 (2020, 60)","104000,00 (2019, 61)","3000000 (2020, 62)"
8,WeChat,NaN,NaN,"1000000 (2020, 63)","900,000,000‬ (2019, 64)",NaN,NaN,NaN,NaN
9,Weibo,NaN,NaN,"800000 (2019, 65)","480000000 (2019, 66)",NaN,"6000,00",NaN,NaN

In [316]:
def extraword_remover(dfs):
  column_count = len(dfs.columns)
  row_count = len(dfs.index)
  for i in range(1, column_count):
    for j in range(row_count):
      if pd.isna(dfs.iloc[j,i]):
        continue
      elif "(" in dfs.iloc[j,i]:
        dfs.iloc[j,i] = dfs.iloc[j,i][0:-11]
  print('Extrawords in user number are removed succesfully')

extraword_remover(df)

Extrawords in user number are removed succesfully

In [317]:
def whitespace_remover(dfs):
  column_count = len(dfs.columns)
  row_count = len(dfs.index)
  for i in range(column_count):
    for j in range(row_count):
      if pd.isna(dfs.iloc[j,i]):
        continue
      else:
        dfs.iloc[j,i] = dfs.iloc[j,i].strip()
        dfs.iloc[j,i] = dfs.iloc[j,i].strip('\u202c')
  print('Whitespaces in all cells are removed succesfully')

whitespace_remover(df)

Whitespaces in all cells are removed succesfully

In [318]:
#Change Header to Country Name
df.at[0,'Social Media Platform']='Social Media Platform'
df.columns = df.iloc[0]
df = df[1:]

df.head(3)

,Social Media Platform,United States,Indonesia,Singapore,China,India,Vietnam,Philippines,Bangladesh
1,Bilibili,NaN,NaN,NaN,27400000,NaN,NaN,NaN,NaN
2,Facebook,190000000,120000000,4450000,3000000,280000000,63000000,72000000,37000000
3,Instagram,107000000,"5984000,0",2110000,3600000,88000000,8000000,"11000,00",1 676 100

In [319]:
def comma_remover(dfs):
  column_count = len(dfs.columns)
  row_count = len(dfs.index)
  for i in range(1, column_count):
    for j in range(row_count):
      if pd.isna(dfs.iloc[j,i]):
        continue
      elif "," in dfs.iloc[j,i]:
        dfs.iloc[j,i] = re.sub(',', '', dfs.iloc[j,i])
  print('Commas in all user number are removed succesfully')

comma_remover(df)

Commas in all user number are removed succesfully

In [320]:
def space_remover(dfs):
  column_count = len(dfs.columns)
  row_count = len(dfs.index)
  for i in range(1, column_count):
    for j in range(row_count):
      if pd.isna(dfs.iloc[j,i]):
        continue
      else:
        dfs.iloc[j,i] = dfs.iloc[j,i].replace(' ','')
  print('Extraspaces in all user number are removed succesfully')

space_remover(df)

Extraspaces in all user number are removed succesfully

In [321]:
def float_converter(dfs):
  column_name = len(dfs.columns)
  row_count = len(dfs.index)
  for i in range(1, column_name):
    for j in range(row_count):
      if isinstance(dfs.iloc[j,i], str):
        dfs.iloc[j,i] = float(dfs.iloc[j,i])
  print('All number are converted to float succesfully')     

float_converter(df)

All number are converted to float succesfully

In [322]:
df.head(10)

,Social Media Platform,United States,Indonesia,Singapore,China,India,Vietnam,Philippines,Bangladesh
1,Bilibili,NaN,NaN,NaN,27400000.0,NaN,NaN,NaN,NaN
2,Facebook,190000000.0,120000000.0,4450000.0,3000000.0,280000000.0,63000000.0,72000000.0,37000000.0
3,Instagram,107000000.0,59840000.0,2110000.0,3600000.0,88000000.0,8000000.0,1100000.0,1676100.0
4,Linkedln,160000000.0,15240000.0,2682000.0,5397000.0,62000000.0,3087500.0,2773485.0,2990000.0
5,Tencent QQ,NaN,NaN,NaN,659100000.0,NaN,NaN,NaN,NaN
6,Tik Tok,45400000.0,81000000.0,800000.0,400000000.0,120000000.0,12000000.0,NaN,NaN
7,Twitter,55700000.0,11800000.0,1370000.0,3200000.0,13150000.0,127000000.0,10400000.0,3000000.0
8,WeChat,NaN,NaN,1000000.0,900000000.0,NaN,NaN,NaN,NaN
9,Weibo,NaN,NaN,800000.0,480000000.0,NaN,600000.0,NaN,NaN
10,Youtube,192000000.0,132000000.0,43000000.0,580000000.0,265000000.0,6200000.0,NaN,29000000.0

In [323]:
#Change Index to Social Media Platform
#df = df.set_index('Social Media Platform')
#df.head(3)

# **1st User Stories**: When I choose a social media network, I am able to get a view the number of users in each country.

In [324]:
def show_df(value):

    print(df[df['Social Media Platform']==value])

social_media = df['Social Media Platform'].tolist()

interact(show_df, value = social_media)

interactive(children=(Dropdown(description='value', options=('Bilibili', 'Facebook', 'Instagram', 'Linkedln', …

# **2nd User Stories**: When I choose a country, I am able to see all the relevant social networks its people use ranked in descending order.

In [325]:
def show_df(value):
    print(df[['Social Media Platform', value]].sort_values(by=[value], ascending=False))

country = list(df)[1:]

interact(show_df, value = country)

interactive(children=(Dropdown(description='value', options=('United States', 'Indonesia', 'Singapore', 'China…

# **3rd User Stories**: I can view a comparison of the percentage of users based on the population for each social media network by the population of the country. (You will have to scrape the population data and provide the source(s))

In [326]:
#Read Excel File
df_pop = pd.read_excel("/content/WorldPopulation2020_Country_WorldBank.xlsx", sheet_name="Sheet1")
df_pop.head(10)

         Country  World Population 2020
0  United States              331501080
1      Indonesia              273523621
2      Singapore                5685807
3          China             1410929362
4          India             1380004385
5        Vietnam               98338583
6    Philippines              109581085
7     Bangladesh              164689383

In [327]:
type(df_pop.iloc[1,1])

numpy.int64

In [328]:
float_converter(df_pop)

All number are converted to float succesfully

In [329]:
df_pop.head(10)

         Country  World Population 2020
0  United States              331501080
1      Indonesia              273523621
2      Singapore                5685807
3          China             1410929362
4          India             1380004385
5        Vietnam               98338583
6    Philippines              109581085
7     Bangladesh              164689383

In [330]:
list(df)

['Social Media Platform',
 'United States',
 'Indonesia',
 'Singapore',
 'China',
 'India',
 'Vietnam',
 'Philippines',
 'Bangladesh']

In [331]:
df_percent = df.copy()
column_name = list(df_percent)[1:]
for i in column_name:
  df_percent['Percent of ' + i] = df[i]*100/ df_pop.loc[df_pop['Country'] == i, 'World Population 2020'].iloc[0]

df_percent.head()

,Social Media Platform,United States,Indonesia,Singapore,China,India,Vietnam,Philippines,Bangladesh,Percent of United States,Percent of Indonesia,Percent of Singapore,Percent of China,Percent of India,Percent of Vietnam,Percent of Philippines,Percent of Bangladesh
1,Bilibili,NaN,NaN,NaN,27400000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.941982,NaN,NaN,NaN,NaN
2,Facebook,190000000.0,120000000.0,4450000.0,3000000.0,280000000.0,63000000.0,72000000.0,37000000.0,57.315047,43.871897,78.265055,0.212626,20.289791,64.064376,65.70477,22.466536
3,Instagram,107000000.0,59840000.0,2110000.0,3600000.0,88000000.0,8000000.0,1100000.0,1676100.0,32.277421,21.877452,37.109948,0.255151,6.376791,8.135159,1.003823,1.017734
4,Linkedln,160000000.0,15240000.0,2682000.0,5397000.0,62000000.0,3087500.0,2773485.0,2990000.0,48.265303,5.571731,47.170085,0.382514,4.492739,3.139663,2.530989,1.815539
5,Tencent QQ,NaN,NaN,NaN,659100000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.713891,NaN,NaN,NaN,NaN

In [332]:
list(df_percent)

['Social Media Platform',
 'United States',
 'Indonesia',
 'Singapore',
 'China',
 'India',
 'Vietnam',
 'Philippines',
 'Bangladesh',
 'Percent of United States',
 'Percent of Indonesia',
 'Percent of Singapore',
 'Percent of China',
 'Percent of India',
 'Percent of Vietnam',
 'Percent of Philippines',
 'Percent of Bangladesh']

In [333]:
def show_df(value):
    print(df_percent[['Social Media Platform', value, 'Percent of ' + value]].sort_values(by=[value], ascending=False))

country = list(df)[1:]

interact(show_df, value = country)

interactive(children=(Dropdown(description='value', options=('United States', 'Indonesia', 'Singapore', 'China…